### ISSUE TITLE
A a playback queue for cues

### ISSUE THREAD

**Issue by suterma** [suterma/replayer-pwa#118]
The idea behind this to prepare a set of cues in a track, that are played back in a predefined/queued order. Kind of like a "playlist" for cues in a track. Using this, one could play back the parts in arbitrary ways.

Maybe this could be implemented in a separate view, with a specific playback engine designed for this feature.

**Comment by anpaulus** [comment]
Actually i would like to add option for this feature, if the button is pressed, the part to be played on queue, and it will not waiting for Enter keypress to confirmed it since the cue marker will continue to play along. I think only need one queue for the time being, and with this enhancement, we can use to rehearse the song and it will flow the song flawlessly.

**Comment by suterma** [comment]
Would you just want to have something like "play this one cue next?", like just a single follow up cue? Something like they do in Samba music where the conductor whistles the next part (or change), you would "click" the next part?

In this case a proposal might be 
- a general option or settings button that enables this "follow up cue mode"
- It simply remembers this pressed cue button up until the current cue ends, then immediately invokes this next cue (now becoming the current cue). 
- At this time now, a new click on a cue will cue up one more further cue and so on...

**Comment by anpaulus** [comment]
The general option or setting button is suitable with the basic plan requirement, and using this setting button differenciate with normal mode.

Here is the basic requirement for flow route song.
When part of verse3 is pressed at the time verse1 still playing, then after verse1 is finished due to cue ended, then it will play verse3 and skip verse2. If there is no button is pressed, then the song will follow normal route, goto verse4-verse5.

Option for visualization of the next cue will help to show next route for cue button.

**Comment by suterma** [comment]
A first version of this has been implemented, in experimental state

- a new "queue cue" mode is available. In this mode:
- When a new cue is clicked, as long as the selected cue is still playing:
- The new cue is scheduled, with a blinking indicator
- When the scheduled cue is invoked, it becomes the selected cue, and the above applies for this cue now.

Areas to improve:
- Clicks should maybe also get handled as new cue, when playback already has passed the selected cue
- The precision is not good enough: Maybe use a staged scheduling like with the cue loop
- The keyboard shortcuts/mnemonics are not honored for this mode currently
