### ISSUE TITLE
Audio recording?

### ISSUE THREAD

**Issue by steffest** [suterma/replayer-pwa#141]
Any plans to add audio recording capabilities?
I found myself in the need of an audio recording and playback tool that I can use whenever inspiration strikes and I usually don't have my laptop nearby.
For me, webbased tools fullfill that "always available" need.
My natural instinct is to write my own, but I'm super charmed with your easy to use, cue based playback concept, so the ability to record directly into your app would be super sweet.

**Comment by suterma** [comment]
Hi steffest,
thanks for your suggestion. I have already thought about it, especially with regard for a later multitrack playback capability.

However, currently I have no plans for actually doing a recording feature. There are so many applications out there that have that, one of them Audiomass, it is mentioned on my comparison page: https://replayer.app/en/documentation/comparison/replayer-vs-audiomass This might be the tool you are looking for.

The organisation for which Replayer is primarily made for has their own recording studio and fully fledged DAW's and use Replayer strictly for playback of their playback tracks.

On the other hand, since Replayer is open source, you are very welcome to fork it and extend it with what you like.

**Comment by steffest** [comment]
Thanks for your swift reply, that's clear.
Yeah, I've looked at Audiomass: nice app, but not really suitable for sequencing or multitrack stuff.
I haven't found an app that suits my need (especially because it also should work on mobile) so -> roll my own, it is :-) 
cheers!

**Comment by suterma** [comment]
@steffest Just to say, but you probably already know, an Audacity clone is now available online at https://wavacity.com/
Quite cool, offers multitracking and recording. I never was very fond of the Audacity UI, but it ticks both your 2 boxes.

**Comment by steffest** [comment]
Dang! I didn't even know that one!
That's awesome indeed.
Yeah, the UI is a bit "erm...", but it does work, even on mobile.
Thanks! That does tick all the boxes.
